ALTER TABLE reco_train_config
  ADD COLUMN IF NOT EXISTS attr_weight DECIMAL(6,4) NOT NULL DEFAULT 0.2000 AFTER train_frequency,
  ADD COLUMN IF NOT EXISTS consume_weight DECIMAL(6,4) NOT NULL DEFAULT 0.3000 AFTER attr_weight,
  ADD COLUMN IF NOT EXISTS rating_weight DECIMAL(6,4) NOT NULL DEFAULT 0.3000 AFTER consume_weight,
  ADD COLUMN IF NOT EXISTS dish_weight DECIMAL(6,4) NOT NULL DEFAULT 0.2000 AFTER rating_weight;
